apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-scaler
  namespace: loadtest-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cron-scaler
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: [""]
- apiGroups: ["apps", "extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-scaler
subjects:
- kind: ServiceAccount
  name: cron-scaler
  namespace: loadtest-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cron-scaler
